gin:
  ip: 0.0.0.0
  port: 3300

db:
  user: root
  password: xL1210...
  host: 127.0.0.1
  port: 3306
  db_name: sale_system
  prefix: ss_

log:
  file_path: ./log/logger.log
  max_size: 5
  max_backups: 10
  max_age: 365

allow_origins:
  - http://localhost:5173
  - http://localhost:8080
  - http://localhost:3000